import { Activity, ActivityDifficultyEnum, ActivityPriorityEnum } from 'Shared/Types/Activity';

export const MOCK_TASKS: Activity[] = [
  {
    _id: '1',
    name: 'Dummy Task',
    description: 'This is just a dummy task',
    priority: ActivityPriorityEnum.HIGH,
    deadline: new Date(),
    difficulty: ActivityDifficultyEnum.HARD,
    schedule: new Date(),
    prerequisites: [],
    subTask: [],
    isHabit: false,
    isDone: false,
  },
  {
    _id: '2',
    name: 'Dummy Task 2',
    description: 'This is just a dummy task 2',
    priority: ActivityPriorityEnum.HIGH,
    deadline: new Date(),
    difficulty: ActivityDifficultyEnum.HARD,
    schedule: new Date(),
    prerequisites: [],
    subTask: [],
    isHabit: false,
    isDone: false,
  },
  {
    _id: '3',
    name: 'Dummy Task 3',
    description: 'This is just a dummy task 3',
    priority: ActivityPriorityEnum.HIGH,
    deadline: new Date(),
    difficulty: ActivityDifficultyEnum.HARD,
    schedule: new Date(),
    prerequisites: [],
    subTask: [],
    isHabit: false,
    isDone: false,
  },
  {
    _id: '4',
    name: 'Dummy Task 4',
    description: 'This is just a dummy task 4',
    priority: ActivityPriorityEnum.HIGH,
    deadline: new Date(),
    difficulty: ActivityDifficultyEnum.HARD,
    schedule: new Date(),
    prerequisites: [],
    subTask: [],
    isHabit: false,
    isDone: false,
  },
];
