export enum IconName {
  Add = 'Add',
  Agenda = 'Agenda',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight',
  ArrowUp = 'ArrowUp',
  Chat = 'Chat',
  Close = 'Close',
  Exclamation = 'Exclamation',
  Exit = 'Exit',
  Filter = 'Filter',
  Money = 'Money',
  Notification = 'Notification',
  Setting = 'Setting',
}
